[[redirects]]
  from = "/index.html"
  to = "https://dpmusic.netlify.app/main.php"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
